posibility to see profiles of other users
bogdansoft/construction_worker_forum_front pull request #75
Opened 2022-12-05 14:42 UTC by DawKozlowski

2022-12-06 09:47 UTC, Robert-Michalski commented on app/components/ViewSinglePost.js
> +                {/* {post.keywords.map(keyword => (
Why is it commented out ?

2022-12-06 10:52 UTC, DawKozlowski commented on app/components/ViewSinglePost.js
> +                {/* {post.keywords.map(keyword => (
Not working without comment dont know why

2022-12-06 11:00 UTC, Robert-Michalski requested changes
Can't merge new code that breaks old functionalities

2022-12-07 08:38 UTC, Robert-Michalski approved these changes

2022-12-07 08:39 UTC, merged